<?php
$company = array(
		/*a*/
		"auspost" => "澳大利亚邮政",
		"aae" => "AAE",
		"anxindakuaixi" => "安信达",
		/*b*/
		"baifudongfang" => "百福东方",
		"bht" => "BHT",
		"bangsongwuliu" => "邦送物流",
		/*c*/
		"cces" => "希伊艾斯",
		"coe" => "中国东方",
		"chuanxiwuliu" => "传喜物流",
		"canpost" => "加拿大邮政",
		"canpostfr" => "加拿大邮政",
		/*d*/
		"datianwuliu" => "大田物流",
		"debangwuliu" => "德邦物流",
		"dpex" => "DPEX",
		"dhl" => "DHL-中国件",
		"dhlen" => "DHL-国际件",
		"dhlde" => "DHL-德国件",
		"dsukuaidi" => "D速快递",
		"disifang" => "递四方",
		/*e*/
		"ems" => "EMS",
		"emsen" => "EMS国际",
		"emsguoji" => "EMS国际",
		"emsinten" => "EMS国际",
		/*f*/
		"fedex" => "Fedex-国际件",
		"fedexcn" => "Fedex-国际件",
		"fedexus" => "Fedex-美国件",
		"feikangda" => "飞康达物流",
		"feikuaida" => "飞快达",
		"fengxingtianxia" => "风行天下",
		"feibaokuaidi" => "飞豹快递",
		/*g*/
		"ganzhongnengda" => "港中能达",
		"guotongkuaidi" => "国通快递",
		"guangdongyouzhengwuliu" => "广东邮政",
		"gls" => "GLS",
		"gongsuda" => "共速达",
		/*h*/
		"huitongkuaidi" => "汇通快运",
		"huiqiangkuaidi" => "汇强快递",
		"hengluwuliu" => "恒路物流",
		"huaxialongwuliu" => "华夏龙",
		// "tiantian" => "海航天天", TODO 和天天快递重复
		"haiwaihuanqiu" => "海外环球",
		"hebeijianhua" => "河北建华",
		"haimengsudi" => "海盟速递",
		"huaqikuaiyun" => "华企快运",
		"haihongwangsong" => "山东海红",
		"hkpost" => "香港邮政",
		/*j*/
		"jiajiwuliu" => "佳吉物流",
		"jiayiwuliu" => "佳怡物流",
		"jiayunmeiwuliu" => "加运美",
		"jinguangsudikuaijian" => "京广速递",
		"jixianda" => "急先达",
		"jinyuekuaidi" => "晋越快递",
		"jietekuaidi" => "捷特快递",
		"jindawuliu" => "金大物流",
		"jialidatong" => "嘉里大通",
		/*k*/
		"kuaijiesudi" => "快捷速递",
		"kangliwuliu" => "康力物流",
		"kuayue" => "跨越物流",
		/*l*/
		"lianhaowuliu" => "联昊通",
		"longbanwuliu" => "龙邦物流",
		"lanbiaokuaidi" => "蓝镖快递",
		"lejiedi" => "乐捷递",
		"lianbangkuaidi" => "联邦快递",
		"lianbangkuaidien" => "联邦快递",
		"lijisong" => "立即送",
		"longlangkuaidi" => "隆浪快递",
		/*m*/
		"menduimen" => "门对门",
		"meiguokuaidi" => "美国快递",
		"mingliangwuliu" => "明亮物流",
		/*n*/
		"neweggozzo" => "新蛋奥硕物流",
		/*o*/
		"ocs" => "OCS",
		"ontrac" => "onTrac",
		/*q*/
		"quanchenkuaidi" => "全晨快递",
		"quanjitong" => "全际通",
		"quanritongkuaidi" => "全日通",
		"quanyikuaidi" => "全一快递",
		"quanfengkuaidi" => "全峰快递",
		/*r*/
		"rufengda" => "如风达快递",
		/*s*/
		"shentong" => "申通",
		"shunfeng" => "顺丰速递",
		"shunfengen" => "顺丰",
		"santaisudi" => "三态速递",
		"shenghuiwuliu" => "盛辉物流",
		"suer" => "速尔物流",
		"shengfengwuliu" => "盛丰物流",
		"shangda" => "上大物流",
		"saiaodi" => "赛澳递",
		"shenganwuliu" => "圣安物流",
		"suijiawuliu" => "穗佳物流",
		/*t*/
		"tiandihuayu" => "天地华宇",
		"tiantian" => "天天快递",
		"tnten" => "TNT",
		"tnt" => "TNT",
		"tonghetianxia" => "通和天下",
		/*u*/
		"ups" => "UPS",
		"upsen" => "UPS",
		"usps" => "USPS",
		/*w*/
		"wanjiawuliu" => "万家物流",
		"wanxiangwuliu" => "万象物流",
		"weitepai" => "微特派",
		/*x*/
		"xinbangwuliu" => "新邦物流",
		"xinfengwuliu" => "信丰物流",
		/*y*/
		"yuantong" => "圆通速递",
		"yunda" => "韵达快运",
		"yuntongkuaidi" => "运通快递",
		"youzhengguonei" => "邮政小包",
		"youzhengguoji" => "邮政小包",
		"yuanchengwuliu" => "远成物流",
		"yafengsudi" => "亚风速递",
		"yibangwuliu" => "一邦速递",
		"youshuwuliu" => "优速物流",
		"yuanweifeng" => "源伟丰快递",
		"yuanzhijiecheng" => "元智捷诚",
		"yuefengwuliu" => "越丰物流",
		"yuananda" => "源安达",
		"yuanfeihangwuliu" => "原飞航",
		"yinjiesudi" => "银捷速递",
		/*z*/
		"zhongxinda" => "忠信达快递",
		"zhimakaimen" => "芝麻开门",
		"zhongtong" => "中通速递",
		"zhaijisong" => "宅急送",
		"zhongyouwuliu" => "中邮物流",
		"zhongsukuaidi" => "中速快件",
		"zhongtianwanyun" => "中天万运" 
);